server:
  servlet:
    # 声明请求当前服务接口时的前缀
    context-path: /z2o
  # 声明请求当前服务接口时的端口, 默认8080
  port: 8000

spring:
  application:
    name: z2o
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 120.77.239.177:8848

graceful-response:
  default-success-code: 200
  default-error-code: 500
  default-validate-error-code: 400
  response-style: 1

